name: Eval

on:
  push:

jobs:
  tock-board:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install nightly toolchain
        uses: dtolnay/rust-toolchain@nightly

      - name: Run eval on tock-board
        run: |
          cd crates/eval
          cargo run -p eval --bin eval tock-board
      
      - name: Upload panic metrics
        uses: actions/upload-artifact@v4
        with:
          name: tock-board-panic-metrics
          path: crates/eval/build/
    
  ringbuffer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install nightly toolchain
        uses: dtolnay/rust-toolchain@nightly

      - name: Run eval on ring_buffer
        run: |
          cd crates/eval
          cargo run -p eval --bin eval ring-buffer
      
      - name: Upload panic metrics
        uses: actions/upload-artifact@v4
        with:
          name: ring-buffer-panic-metrics
          path: crates/eval/build/

  survey:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install nightly toolchain
        uses: dtolnay/rust-toolchain@nightly

      - name: Run survey
        run: |
          cd crates/eval
          cargo run -p eval --bin eval survey
      
      - name: Upload panic metrics
        uses: actions/upload-artifact@v4
        with:
          name: survey-panic-metrics
          path: crates/eval/build/


