name: Eval

on:
  push:
  pull_request:

jobs:
  ringbuffer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install nightly toolchain
        uses: dtolnay/rust-toolchain@nightly

      - name: Run eval on ring_buffer
        run: |
          cd crates/eval
          cargo run -p eval ring-buffer
      
      - name: Upload panic metrics
        uses: actions/upload-artifact@v4
        with:
          name: ring-buffer-panic-metrics
          path: crates/eval/fixtures/eval-runs/latest/benchmarks/ring-buffer/

