name: Eval

on:
  push:
  pull_request:

jobs:
  ringbuffer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install nightly toolchain
        uses: dtolnay/rust-toolchain@nightly

      - name: Run eval on ring_buffer
        run: >
          cargo run
          -p eval
          --
          crates/eval/fixtures/ring_buffer/src/lib.rs

      - name: Zip fixed project
        run: |
          zip -r ring_buffer_no_seatbelts_fixed.zip crates/eval/fixtures/ring_buffer-no-seatbelts-fixed

      - name: Upload fixed project artifact
        uses: actions/upload-artifact@v4
        with:
          name: ring-buffer-no-seatbelts-fixed
          path: ring_buffer_no_seatbelts_fixed.zip
